// Generado por web/build.py desde web/src/i18n/es.json (sólo las claves js.*). No se edita a mano: después
// de cambiar es.json se regenera con  python3 web/build.py --textos-es  (el build y npm test revisan que
// coincidan). Es el respaldo en español de i18n.js: viene con el JS y no depende de la red.
export default {
  "js.reserva.fechas_requeridas": "Elige la fecha de llegada y la de salida.",
  "js.reserva.fecha_pasada": "La llegada no puede ser en el pasado.",
  "js.reserva.fecha_lejana": "Por ahora se reciben solicitudes hasta un año adelante.",
  "js.reserva.min_noches": "La estadía mínima es de {minNoches} noches.",
  "js.reserva.max_noches": "La estadía máxima es de {maxNoches} noches.",
  "js.reserva.fechas_ocupadas": "Esas fechas ya tienen una solicitud. Elige otras.",
  "js.reserva.datos_invalidos": "Revisa los datos del formulario.",
  "js.reserva.nombre": "Escribe tu nombre (2 a 80 caracteres).",
  "js.reserva.email": "Escribe un correo válido.",
  "js.reserva.telefono": "El teléfono sólo admite números, espacios y + ( ) - .",
  "js.reserva.mensaje": "El mensaje admite hasta 1 000 caracteres.",
  "js.reserva.huespedes": "Pueden alojar de 1 a {maxHuespedes} personas.",
  "js.reserva.acepta": "Necesitamos tu consentimiento para responder la solicitud.",
  "js.reserva.red": "No se pudo conectar con el servidor de reservas. Intenta de nuevo.",
  "js.reserva.sin_configurar": "Las reservas todavía no están conectadas en este sitio.",
  "js.reserva.noches.one": "{n} noche",
  "js.reserva.noches.other": "{n} noches",
  "js.reserva.personas.one": "{n} persona",
  "js.reserva.personas.other": "{n} personas",
  "js.reserva.cal.dias_cortos": "lu,ma,mi,ju,vi,sá,do",
  "js.reserva.cal.motivo.pasado": "ya pasó",
  "js.reserva.cal.motivo.ocupado": "ocupado",
  "js.reserva.cal.motivo.lejano": "más de un año adelante",
  "js.reserva.cal.motivo.minimo": "mínimo {n} noches",
  "js.reserva.cal.motivo.sin_salida": "no quedan {n} noches libres desde aquí",
  "js.reserva.cal.dia_llegada": "{fecha}, llegada elegida",
  "js.reserva.cal.dia_salida": "{fecha}, salida elegida",
  "js.reserva.cal.dia_en_rango": "{fecha}, dentro de tu estadía",
  "js.reserva.cal.dia_no_disponible": "{fecha}, no disponible: {motivo}",
  "js.reserva.cal.elige_llegada": "Elige la llegada",
  "js.reserva.cal.elige_salida": "Llegada {entrada} · elige la salida",
  "js.reserva.cal.rango": "{entrada} → {salida} · {noches}",
  "js.reserva.resumen.noches_por_tarifa": "{noches} × {tarifa}",
  "js.reserva.resumen.noches": "Noches",
  "js.reserva.resumen.elige_fechas": "Elige tus fechas",
  "js.reserva.resumen.total_ejemplo": "{noches} · total de ejemplo",
  "js.reserva.resumen.sin_cobro": "sin cobro en línea",
  "js.reserva.envio.enviando": "Enviando…",
  "js.reserva.envio.solicitar": "Solicitar",
  "js.reserva.exito.texto": "Pediste {noches}, del {entrada} al {salida}, para {personas}.",
  "js.contenido.alt_generico": "Foto del departamento",
  "js.contenido.mas_fotos": "Más fotos de este espacio",
  "js.contenido.ver_foto": "Ver foto: {alt}",
  "js.tour.error.colisiones": "No se pudieron leer los datos de colisión. Recarga la página.",
  "js.tour.error.modelo": "No se pudo cargar el modelo 3D. Revisa la conexión y recarga la página.",
  "js.tour.carga.modelo": "Cargando el modelo… {porcentaje} %",
  "js.tour.carga.escena": "Preparando la escena…",
  "js.tour.carga.listo": "Listo · {n} obstáculos estáticos",
  "js.tour.aviso.seguir_mirando": "Clic en la vista para seguir mirando",
  "js.tour.motivo.camino": "Estás en el camino: retrocede un paso",
  "js.tour.motivo.hoja": "Corre primero la puerta del clóset",
  "js.tour.accion.abrir": "Abrir {cosa}",
  "js.tour.accion.cerrar": "Cerrar {cosa}",
  "js.tour.clase.puerta": "puerta",
  "js.tour.clase.ventana": "ventana",
  "js.tour.clase.cajon": "cajón",
  "js.tour.clase.closet": "clóset",
  "js.tour.clase.nevera": "nevera",
  "js.tour.clase.mueble": "mueble",
  "js.tour.clase.pieza": "pieza",
  "js.tour.luz.encender": "Encender {luces}",
  "js.tour.luz.apagar": "Apagar {luces}",
  "js.tour.luz.encender_la_luz": "Encender la luz",
  "js.tour.luz.apagar_la_luz": "Apagar la luz",
  "js.tour.luz.interruptor": "Luz: {nombre}",
  "js.tour.luz.living_techo": "Living · techo",
  "js.tour.luz.living_lampara_pie": "Living · lámpara de pie",
  "js.tour.luz.cocina_techo": "Cocina · techo",
  "js.tour.luz.hall_techo": "Hall · focos",
  "js.tour.luz.dorm1_techo": "Dormitorio principal · techo",
  "js.tour.luz.dorm1_velador_izq": "Dormitorio principal · velador izquierdo",
  "js.tour.luz.dorm1_velador_der": "Dormitorio principal · velador derecho",
  "js.tour.luz.paso_d1": "Clósets del principal · techo",
  "js.tour.luz.dorm2_techo": "Segundo dormitorio · techo",
  "js.tour.luz.dorm2_aplique_izq": "Segundo dormitorio · aplique izquierdo",
  "js.tour.luz.dorm2_aplique_der": "Segundo dormitorio · aplique derecho",
  "js.tour.luz.paso_d2": "Clósets del segundo · techo",
  "js.tour.luz.bano1": "Baño principal · techo",
  "js.tour.luz.bano2": "Segundo baño · techo",
  "js.tour.luz.balcon": "Balcón · colgante del comedor",
  "js.tour.recinto.Hall": "Hall",
  "js.tour.recinto.Living": "Living",
  "js.tour.recinto.Cocina": "Cocina",
  "js.tour.recinto.Dorm1": "Dormitorio principal",
  "js.tour.recinto.Dorm2": "Segundo dormitorio",
  "js.tour.recinto.Paso_D1": "Clósets del principal",
  "js.tour.recinto.Paso_D2": "Clósets del segundo",
  "js.tour.recinto.Bano1": "Baño principal",
  "js.tour.recinto.Bano2": "Segundo baño",
  "js.tour.recinto.Balcon": "Balcón",
  "js.tour.recinto.Palier": "Palier",
  "js.tour.recinto.Nicho_LV": "Lavadora",
  "js.tour.pieza.puerta_del_dormitorio_principal": "puerta del dormitorio principal",
  "js.tour.pieza.puerta_del_segundo_dormitorio": "puerta del segundo dormitorio",
  "js.tour.pieza.puerta_del_bano_1": "puerta del baño 1",
  "js.tour.pieza.puerta_del_bano_2": "puerta del baño 2",
  "js.tour.pieza.puerta_de_entrada": "puerta de entrada",
  "js.tour.pieza.ventanal_del_living": "ventanal del living",
  "js.tour.pieza.puerta_del_closet": "puerta del clóset",
  "js.tour.pieza.cajon_del_closet": "cajón del clóset",
  "js.tour.pieza.cajon_de_cubiertos": "cajón de cubiertos",
  "js.tour.pieza.cajon_1_profundo_de_la_cocina": "cajón 1 profundo de la cocina",
  "js.tour.pieza.cajon_2_de_la_cocina": "cajón 2 de la cocina",
  "js.tour.pieza.cajon_de_ollas_y_sartenes": "cajón de ollas y sartenes",
  "js.tour.pieza.cajon_3_de_la_cocina": "cajón 3 de la cocina",
  "js.tour.pieza.cajon_3_profundo_de_la_cocina": "cajón 3 profundo de la cocina",
  "js.tour.pieza.puerta_bajo_el_lavaplatos": "puerta bajo el lavaplatos",
  "js.tour.pieza.puerta_del_mueble_alto_platos": "puerta del mueble alto (platos)",
  "js.tour.pieza.puerta_del_mueble_alto": "puerta del mueble alto",
  "js.tour.pieza.puerta_del_mueble_alto_tazas": "puerta del mueble alto (tazas)",
  "js.tour.pieza.puerta_de_la_nevera": "puerta de la nevera",
  "js.tour.pieza.cajon_del_freezer": "cajón del freezer"
};
